In [ ]:
# Scikit-learn
"""
│
├── Module 1 : Introduction to Scikit-learn
├── Module 2 : Dataset Loading
├── Module 3 : Data Preprocessing
├── Module 4 : Train Test Split
├── Module 5 : Feature Scaling
├── Module 6 : Encoding
├── Module 7 : Missing Values
├── Module 8 : Feature Selection
├── Module 9 : Regression Algorithms
├── Module 10 : Classification Algorithms
├── Module 11 : Clustering
├── Module 12 : Model Evaluation
├── Module 13 : Hyperparameter Tuning
├── Module 14 : Pipelines
├── Module 15 : Cross Validation
├── Module 16 : Model Saving
├── Module 17 : Complete ML Projects
├── Module 18 : Interview Questions
"""

'\n│\n├── Module 1 : Introduction to Scikit-learn\n├── Module 2 : Dataset Loading\n├── Module 3 : Data Preprocessing\n├── Module 4 : Train Test Split\n├── Module 5 : Feature Scaling\n├── Module 6 : Encoding\n├── Module 7 : Missing Values\n├── Module 8 : Feature Selection\n├── Module 9 : Regression Algorithms\n├── Module 10 : Classification Algorithms\n├── Module 11 : Clustering\n├── Module 12 : Model Evaluation\n├── Module 13 : Hyperparameter Tuning\n├── Module 14 : Pipelines\n├── Module 15 : Cross Validation\n├── Module 16 : Model Saving\n├── Module 17 : Complete ML Projects\n├── Module 18 : Interview Questions\n'

# Module 1 : Introduction to Scikit-learn
What is Scikit-learn?

Scikit-learn is one of the most popular Python libraries for Machine Learning.

It provides ready-made algorithms that help us build Machine Learning models without implementing complex mathematics from scratch.

In [2]:
"""Why do we use Scikit-learn?
Without sklearn

Write algorithm

↓

Write math formulas

↓

Matrix calculations

↓

Optimization

↓

Prediction"""

'Why do we use Scikit-learn?\nWithout sklearn\n\nWrite algorithm\n\n↓\n\nWrite math formulas\n\n↓\n\nMatrix calculations\n\n↓\n\nOptimization\n\n↓\n\nPrediction'

In [11]:
"""| Student | Hours Studied | Attendance | Marks |
| ------- | ------------- | ---------- | ----- |
| A       | 2             | 80         | 30    |
| B       | 3             | 82         | 40    |
| C       | 5             | 90         | 60    |
| D       | 7             | 95         | 80    |
| E       | 9             | 98         | 95    |

Suppose we have a student data.

what happens in a dataset?
Dataset

── Features (Input)
      Hours
      Attendance
── Target (Output)
       Marks

Ex:- Hours studied Attendence

jab predict karna hota hai target(y)
"""

'| Student | Hours Studied | Attendance | Marks |\n| ------- | ------------- | ---------- | ----- |\n| A       | 2             | 80         | 30    |\n| B       | 3             | 82         | 40    |\n| C       | 5             | 90         | 60    |\n| D       | 7             | 95         | 80    |\n| E       | 9             | 98         | 95    |\n\nSuppose we have a student data.\n\nwhat happens in a dataset?\nDataset\n\n── Features (Input)\n      Hours\n      Attendance\n── Target (Output)\n       Marks\n\nEx:- Hours studied Attendence\n\njab predict karna hota hai target(y)\n'

In [5]:
"""Hours Studied:- 2,3,5,7,9
Exam Score:- 30,40,60,80,95
Student studies 6hrs"""

from sklearn.linear_model import LinearRegression
import numpy as np


X=np.array([[2],[3],[5],[7],[9]])
y=np.array([[30],[40],[60],[80],[95]])

model=LinearRegression()
model.fit(X,y)
prediction=model.predict([[6]])
print("Predicted Marks:",prediction)



Predicted Marks: [[68.53658537]]


# Module 2: sklearn.datasets
What is dataset?

A dataset is a collection of data used to train and test a Machine Learning model.

Features are the input variables.

The target is the output variable.
# Iris DataSet
Iris Dataset Machine Learning ka sabse famous beginner dataset hai. Lagbhag har ML course aur interview me is dataset ka use hota hai.

The Iris Dataset is a collection of measurements of 150 iris flowers.

It is used to train and test Machine Learning classification model

The Iris dataset contains flower measurements.

Is dataset me 3 types ke Iris flowers hote hain. Machine Learning ka goal hota hai:Flower ki measurements dekhkar batana ki ye kis type ka flower hai.

1. Setosa 2. Versicolor 3. Virginica

We use load_iris() to load the dataset.

In [ ]:
# Step 1: Import Dataset
from sklearn.datasets import load_iris

# Step 2: Load Dataset
iris = load_iris() 

# Step 3: Print Feature Names
print("Feature Names:")
print(iris.feature_names)

print()

# Step 4: Print Target Names
print("Target Names:")
print(iris.target_names)

print()

# Step 5: Print First 5 Rows
print("First Five Rows:")
print(iris.data[:5])

print()

# Step 6: Print First 5 Target Values
print("Target:")
print(iris.target[:5])

Feature Names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target Names:
['setosa' 'versicolor' 'virginica']

First Five Rows:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Target:
[0 0 0 0 0]


# Module 3: train_test_split


What is train_test_split()?

train_test_split() is a function in Scikit-learn that divides a dataset into training data and testing data.

We use training data to teach the model and testing data to check how well the model performs on new, unseen data.

# What is y_train?
y_train contains the correct outputs for the training data.

The model compares the features with these labels during learning.
# What is X_train?
X_train contains the training features.

The model learns from this data.
# What is X_test?
X_test contains new input data that the model has never seen before.
# What is y_test?
y_test contains the real answers for the testing data.

We compare the model's predictions with these answers.

# Visual Diagram


             Dataset
                │
      ┌─────────┴─────────┐
      │                   │
 Training Data       Testing Data
    (80%)               (20%)

In [8]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load dataset
iris = load_iris()

# Convert to DataFrame
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add target column
df["Flower"] = iris.target

# Features
X = df.drop("Flower", axis=1) #This line removes the Flower column because it is the target variable that we want to predict.

# Target
y = df["Flower"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)


# Module 4: Feature Scaling (StandardScaler & MinMaxScaler)

Feature Scaling is the process of bringing different features to a similar scale.

Sometimes one feature has very small values and another has very large values. This difference can confuse some Machine Learning algorithms.

Suppose we have student data.

Hours Studied:-2,5,8-	Annual Income:- 20k,50k,80k

# Two Types of Scaling
1. StandardScaler:-It transforms data so that:Mean=0,std deviation=0
Scaled Value = (X - Mean) / Standard Deviation

2. MinMaxScaler:-Scaled Value = (X - Minimum) / (Maximum - Minimum) 

It converts every value between 0 and 1

In [9]:
# Step 1: Import Libraries
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

# Step 2: Load Dataset
iris = load_iris()

# Step 3: Convert to DataFrame
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Step 4: Select Features
X = df

# Step 5: Create StandardScaler Object
scaler = StandardScaler()

# Step 6: Fit and Transform Data
X_scaled = scaler.fit_transform(X)

# Step 7: Convert Back to DataFrame
scaled_df = pd.DataFrame(
    X_scaled,
    columns=df.columns
)

# Step 8: Display First 5 Rows
print(scaled_df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444


# What is Encoding?
Encoding ka matlab hai text data ko numbers me convert karna, kyunki Machine Learning algorithms sirf numbers ko samajhte hain.
Encoding

# Types of Encoding
1. Label Encoding 2. One-Hot Encoding 3. Ordinal Encoding

In [ ]:
# 1. Label Encoding:- Label Encoding converts each category into a unique number.
# one column
# Can create false order
# Good for target labels

from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Create Dataset
df = pd.DataFrame({
    "Gender": ["Male", "Female", "Male", "Female", "Male"]
})

print("Original Data")
print(df)

# Create LabelEncoder
encoder = LabelEncoder()

# Apply Encoding
df["Gender"] = encoder.fit_transform(df["Gender"])

print("\nEncoded Data")
print(df)

Original Data
   Gender
0    Male
1  Female
2    Male
3  Female
4    Male

Encoded Data
   Gender
0       1
1       0
2       1
3       0
4       1


In [ ]:
# 2. One-Hot Encoding:-One-Hot Encoding creates a separate column for every category.
#it contains multiple columns
#No order
#Best for nominal features

import pandas as pd

df = pd.DataFrame({
    "Color":["Red","Blue","Green","Red"]
})

encoded = pd.get_dummies(df)

print(encoded)

   Color_Blue  Color_Green  Color_Red
0       False        False       True
1        True        False      False
2       False         True      False
3       False        False       True


In [ ]:
# 3. Ordinal Encoding:- Ordinal Encoding is used when categories have a natural order.
# One column
# Uses real order
# Best for ordered categories

from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

df = pd.DataFrame({
    "Education":[
        "High School", #High School=0 
        "Bachelor",    #Bachelor=1
        "Master",      #Master=2
        "PhD"          #PhD
    ]
})

encoder = OrdinalEncoder(
    categories=[[
        "High School",
        "Bachelor",
        "Master",
        "PhD"
    ]]
)

df["Education"] = encoder.fit_transform(df)

print(df)

   Education
0        0.0
1        1.0
2        2.0
3        3.0
