# Introduction to NumPy
Numpy (Numerical Python) is a python library that is the core library for scientific computing in python.

It contains a collection of tools and techniques that can be used to solve mathematical models of problems in science and engineering.

One of these tools is a high-performance multidimensional array object that is a powerful data structure for the effiecient computation of arrays and matrices.

To work with these arrays, there is a vast amount of hight level mathematical functons operate on these matrices and arrays.

# Why learn NumPy

1. Model Inputs Need Numpy Arrays

ML libraries like Scikit-learn, TensorFlow, PyTorch, etc. expect data in Numpy array format.

Even pandas and OpenCv internally rely on numpy arrays.

2. NumPy is Much Faster for Large numerical computation 

Numpy is written in optimized C code under the hood.

It supports:- Matrix multiplication, Dot products, Broadcasting (auto-expanding arrays in operations)

Much faster than native python loops or lists.

Numpy handles N-dimensional arrays. (1D,2D,3D,....,nD)

3. You need NumPy to build custom algorithms

For hands-on-ML or from-scratch models, Numpy is essential.

You use it for:- Linear regression, Gredient descent, Backpropagation, Activation functions

In [1]:
# create arrays for python list
# np.array({ele1,ele,2,ele3})
# NumPy arrays are created using the np.array() function. They can be created from Python sequences such as lists and tuples.
# An array is a collection of similar data stored in one variable.

import numpy as np
arr=np.array([1,2,3,4])
print(arr)





[1 2 3 4]


In [2]:
# with default values
# np.zeores(shap) (3) fir id,(3,30) 2d

import numpy as np
zeroes_array=np.zeros(3)
print(zeroes_array)

[0. 0. 0.]


In [3]:
import numpy as np
# ndim (Number of Dimensions)Used to find dimensions.

arr = np.array([[1,2],[3,4]])
print(arr.ndim)

2


In [4]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

# Find Total Elements

arr=np.array([[1,2,3],[4,5,6]])
print(arr.size)
print(arr.dtype) #find data type


(2, 3)
6
int64


In [5]:
# creating sequences of numbers in numpy
# arrange()
# arrange(start,stop,step)

import numpy as np
arr= np.arange(1,11,3)
print(arr)

[ 1  4  7 10]


In [6]:
#creating identity matrices
#eye(size)

import numpy as np
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
list1=[1,2,3,4,5]
print(list1)
import numpy as np
numpy_array=np.array([1,2,3,4,5])
print(numpy_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [8]:
# 1d

import numpy as np
arr_1d=np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [9]:
import numpy as np
arr_2d=np.array([[1,2,3],
                [5,6,7],
                [9,10,11]])
print(arr_2d)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [10]:
import numpy as np #import= load memory, numpy=library name, as np=short name
arr = np.array([
[
 [1,2],
 [3,4]
],
[
 [5,6],
 [7,8]
]
])

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
