# SciPy 
SciPy is a python library used for scientific computing, mathematics, optimization, statistics, signal processing and linear algebra.

It is built on top NumPy.

# Why do we use SciPy
Scipy provides ready made mathmatical functions.

In [13]:
# Model 1- scipy.constants

from scipy import constants
print(constants.pi)

3.141592653589793


In [14]:
constants.g # g is gravity


9.80665

In [15]:
constants.c #speed of light

299792458.0

In [ ]:
#Module 2 - scipy.cluster
#used fot clustering data
import numpy as np
from sklearn.cluster import KMeans

#create data set
data = np.array([
    [1,2],
    [2,3],
    [3,4],
    [8,9],
    [9,10],
    [10,11],
    [11,12]
])

#We create a K-Means model
model = KMeans(n_clusters=2, random_state=42)

#train the model
model.fit(data)

print("Centroids:")
print(model.cluster_centers_)

print("\nLabels:")
print(model.labels_)

Centroids:
[[ 2.   3. ]
 [ 9.5 10.5]]

Labels:
[0 0 0 1 1 1 1]


In [ ]:
# Module 3- scipy.stats
# Mean
# Median
# Mode
# Standard Deviation
# Correlation
# Probability
#SciPy helps me calculate statistical values quickly.

In [8]:
#Mean 
from scipy import stats
data =[10,20,40,30]
print(stats.tmean(data))

25.0


In [11]:
#Mode 
data= [10,30,50,70,10]
print(stats.mode(data))

ModeResult(mode=np.int64(10), count=np.int64(2))


In [12]:
#Median

data= [10,50,20,30,5]
stats.median_abs_deviation(data)

np.float64(10.0)

In [13]:
#Standard deviation
marks = [10,20,30,40,50]

print(stats.tstd(marks))

15.811388300841896


In [14]:
#Variance

data= [10,25,35,45]
stats.tvar(data)

np.float64(222.91666666666666)

In [16]:
# Find the mean of five numbers.

marks=[5,8,7,9,6,4]
print(stats.tmean(marks))

6.5


In [21]:
# Module 4- scipy.linalg
#Matrix
from scipy import linalg
A= np.array([
    [1,2,5],
    [2,3,6],
    [3,4,8]
])
A
print(linalg.det(A))

-0.9999999999999998


In [22]:
#Inverse Matrix
A= np.array([
    [1,2,5],
    [2,3,6],
    [3,4,8]
])

linalg.inv(A)

array([[ 2.22044605e-16, -4.00000000e+00,  3.00000000e+00],
       [-2.00000000e+00,  7.00000000e+00, -4.00000000e+00],
       [ 1.00000000e+00, -2.00000000e+00,  1.00000000e+00]])

In [ ]:
#Eigen Values
#Linear algebra is important in machine learning. SciPy makes matrix caluclations easy.

A= np.array([
    [1,2,5],
    [2,3,6],
    [3,4,8]
])

linalg.eigvals(A)

array([12.62727745+0.j, -0.73502084+0.j,  0.10774339+0.j])

In [30]:
# Module 5- scipy.optimize

from scipy.optimize import minimize
# Suppose (x**2+5)
# we want the minimum value

def fun(x):
    return x**2+5

result=minimize(fun, x0=10)
result.x

array([-6.16406142e-08])

In [37]:
#example of root 
from scipy.optimize import root
def equation(x):
    return x**2-25
r=root(equation,0)
r.x

array([5.])

In [ ]:
#solve x²-16=0
def solution(x):
    return x**2-16
eq=root(solution,0)
eq.x

array([4.])

In [42]:
# Module 6 — scipy.integrate
# used for integration
from scipy.integrate import quad

result,error= quad(lambda x:x**2,0,5)
result

41.66666666666666

In [ ]:
#Module 7 — scipy.spatial
#Distance caluclation used in Recommendation Systems
# KNN
# Clustering

from scipy.spatial.distance import euclidean

a=[4,5]
b=[5,6]
euclidean(a,b)

np.float64(1.4142135623730951)

In [54]:
#Used for predicting missing values in the given datasets.
#Module 8 — scipy.interpolate

from scipy.interpolate import interp1d
import numpy as np
x=np.array([1,2,3])
y=np.array([10,20,30])
f=interp1d(x,y)
f(2.1)


array(21.)

In [55]:
# Module 9 — scipy.fft
# Fast Fourier Transform
# Mostly used in
# Audio Processing
# Image Processing
# Signal Processing

from scipy.fft import fft
import numpy as np
x=np.array([1,2,3,4])
print(fft(x))

[10.-0.j -2.+2.j -2.-0.j -2.-2.j]


In [ ]:
# mini project 
# imagine i have a exam scors

# 1.Find the mean.
# 2.Find the variance.
# 3.Find the standard deviation.
# 4.Create a 2×2 matrix and find its determinant.
# 5.Find the inverse of the matrix.
# 6.Calculate the Euclidean distance between two students' score pairs.
# 7.Integrate x**2 0 to 5.
# 8.Solve the equation x**2-81=0

np.float64(78.625)

In [59]:
# 1.Find the mean
scores = [65, 70, 72, 75, 80, 82, 90, 95]
print(stats.tmean(scores))

78.625


In [61]:
# 2.Find the variance.
print(stats.tvar(scores))


103.98214285714285


In [62]:
# 3.Find the standard deviation.
print(stats.tstd(scores))

10.197163471139552


In [63]:
# 4.Create a 2×2 matrix and find its determinant.
matrix = np.array([
    [2, 3],
    [4, 5]
])

det = np.linalg.det(matrix)

print("Matrix:")
print(matrix)

print("Determinant:", det)

Matrix:
[[2 3]
 [4 5]]
Determinant: -2.0


In [ ]:
# Module 10 scipy.integrate
# Integration means Area under Curve.

from scipy import integrate

result, error = integrate.quad(lambda x: x**2,0,5)

print(result)


41.66666666666666


In [2]:
# Module 5 scipy.interpolate
# Interpolation means
# Finding Missing Values.

import numpy as np

from scipy.interpolate import interp1d

x = np.array([0,1,2,3])

y = np.array([10,20,30,40])

f = interp1d(x,y)

print(f(1.5))


25.0
